(setq gc-cons-threshold 20000000)

(let ((root (file-name-directory load-file-name)))
  (setq custom-file (expand-file-name "auto.el" root))
  (mapc (lambda (dir)
          (add-to-list 'load-path (expand-file-name dir root)))
        '("config" "lib" "snippets")))

(require 'config-base)
(require 'ext-elisp)
(require 'general)
(require 'config-helpers)
(require 'buffer)
(require 'buffer-trail)
(require 'missile)
(require 'tests-anywhere)
(require 'text-editing)
(require 'movement)
(require 'window-management)
(require 'git)
(require 'crux)
(require 'ext-god-mode)
(require 'ext-helm)
(require 'ext-projectile)
(require 'ext-linum)
(require 'ext-server)
(require 'ext-comint)
(require 'ext-isearch)
(require 'ext-minibuffer)
(require 'ext-ibuffer)
(require 'ext-compile)
(require 'ext-ido)
(require 'lang-elixir)
(require 'lang-ruby)

(load "environment.el")
(load "appearance.el")
(load "behavior.el")
(load "terminal.el")
(load "keybindings.el")
(load "alias.el")

(mapc 'load
      (file-expand-wildcards
       (expand-file-name "config/langs/*.el" emacs-d)))

(load-if-exists "~/.emacs.custom.el")
